site_name: PyGnome
site_description: Python library for genome annotations
site_url: https://pcingola.github.io/pygnome
repo_url: https://github.com/pcingola/pygnome
repo_name: pcingola/pygnome

# Important: Configure MkDocs to build directly to the docs directory
docs_dir: docs_src
site_dir: docs

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: pygnome_alpha.png
  favicon: pygnome_alpha.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_category_heading: true
            show_root_heading: true
  - gen-files:
      scripts:
        - docs_src/gen_ref_pages.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - footnotes

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Basic Usage: user-guide/basic-usage.md
    - Advanced Usage: user-guide/advanced-usage.md
  - API Reference:
    - Overview: api/index.md
    - Genomics: api/genomics.md
    - Parsers: api/parsers.md
    - Sequences: api/sequences.md
    - Feature Store: api/feature-store.md
  - Development:
    - Contributing: development/contributing.md
